### ISSUE TITLE
[META] Support for blocking off areas of the hospital

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#826]
This is a meta issue for supporting blocked off areas of the hospital, as in the original Theme Hospital. Any bug affecting blocked off areas should reference this issue. Once all of the critical bugs preventing this feature are implemented, then we can remove the build restrictions.

_Until a debug flag is implemented, to test a blocked off area, build plants or drink machines against the wall separating a plot that hasn't been purchased yet, then purchase that plot._
- [x] Implement debug flag to allow placing objects that would block off a portion of the map
- [ ] Fix bugs that arise because a part of the map is blocked off
- [ ] Remove the debug flag and default to allowing blocked maps

**Comment by TheCycoONE** [comment]
#819

**Comment by lewri** [comment]
#2021

**Comment by lewri** [comment]
#1963

**Comment by lewri** [comment]
Just adding my thoughts here, that blocking off areas shouldn't be used inside rooms as it can break the room.

**Comment by lewri** [comment]
#2072

**Comment by lewri** [comment]
#2211

**Comment by Alberth289346** [comment]
Reporting more glitches isn't really needed. We know they exist in half a zillion variations, and more if you start looking for them,
Cyco looked at the problem already and established that the current way of painting rooms to the screen is simply broken beyond repair. The current solution is never going to fix all render bugs.

As such, it's not going to be a small local fix with a testcase like you made to verify it's indeed fixed. Instead, the entire paint code must be taken out and replaced by something better. Trouble is, we don't yet know what that "something" should be. I think we also established that likely the current paint code doesn't get enough information to solve the problem, so that needs some thinking too.

This is basically the point where we are currently wrt this problem. No easy solution available, I am afraid.

**Comment by ARGAMX** [comment]
I suggest to close every blocking off areas sub-issues (as we do that for Graphical Glitches sub-issues):

1. Each of them cannot be solved individually.
2. If the objects are already placed in an invalid way, then this situation can no longer be resolved. A mechanism is needed that simply will prevent such placement.

An example of such mechanism is described here:

Theme Hospital `Safe Blocked Off Areas` Algorithm:

1. When placing corridor items or new room these checks should be executed:
1.1. This placing not making any already exited room door path-disconnected from the map Entrance. (room_door==world) [“==” - is mean connected]
1.2. This placing does not make any humanoid path-disconnected from the map Entrance. (humanoid==world)

2. When building room also these checks should be executed:
2.1. This room door should be path-connected with the map Entrance. (room_door==world)

3. When placing items in the room these checks should be executed:
3.1. The access point (or access points) of this item is not path-disconnected from the room entrance. (object_access_points==room_door) (patient access point, medic access point, handyman access point)
3.2. The access point (or access points) of already placed items in the room is not path-disconnected from the room entrance. (objects_access_points==room_door)

4. When placing staff these checks should be executed:
4.1. This tile is not any of the blocked tiles.
	4.1.1 If it is a corridor tile, then this tile is blocked if not connected with the map Entrance. (tile<>world)
	4.1.2 If it is a room tile, then this tile is blocked if not connected with the room entrance. (tile<>room_door)


Things should be taken into account:
Unreachable plants or litter shouldn't crash the game. It should be a valid case. Handyman shouldn't go crazy or get stuck on an unreachable plant or litter.


As a result of all of this:
`Safe Blocking Off Areas` functionality is available as in the original game.
Any room door or humanoid won't be in the blocked area as in the original game. 
(not taking into account some bugs of the original game which still allow this to be done).


https://docs.google.com/document/d/1BXA5-pg5cocINPt_Tg_lOVYvLqckJfgzz7qmaCck1Tc

**Comment by Alberth289346** [comment]
The bugs in themselves are valid, as far as I can see. They do happen. You close bugs only when they are fixed or when you have no intention to ever fix them.

Closing them will generally cause users to "find" and report them again.

It is very likely true that at individual bug report level, it's not fixable. However, that is not the only way to fix bugs. It's perfectly fine to fix them by stepping in at a higher level and take out the root cause common to all those bugs.  
This is what I am trying to do with the render experiments. Fix the render algorithm so that all existing render bugs vanish.

The collection of existing bug reports can help there in understanding what is wrong in the current implementation.

**Comment by Alberth289346** [comment]
BTW: The proposal in Section 3 of the document is what is currently being done. The cabinet teleport bug is the counter-example of that being sufficient.

**Comment by ARGAMX** [comment]
> BTW: The proposal in Section 3 of the document is what is currently being done. The cabinet teleport bug is the counter-example of that being sufficient.

Not quite.
This could be said not only about point 3, but also about points 1 and 2.

Currently, on placing objects there's a check to ensure that placing an object doesn't create a closed, dead-end space.
This check is more stringent than the `Safe Blocked Off Areas` algorithm.

Therefore, requirements 1, 2, and 3 are met.
However, this check also blocks the creation of closed, dead-end spaces, which are allowed in the original Theme Hospital.
Thus not following to the original Theme Hospital.

This wouldn't be a big deal, but it makes it impossible to build rooms with the same layout as in the original game.

For example, in Theme Hospital, building an X-ray room with a minimum size of 6x6 isn't that difficult.
But if you try building a 6x6 X-ray room in CorsixTH, you'll notice it's not so simple. 
First, you need to carefully place the door beforehand. If you do, then place the X-ray machine but not close to the wall, and then try a protective shield and a computer where the doctor sits.
And if you haven't placed the door wisely, at this stage you will have 0 available variants.
Similar issues exist with other rooms, but with the X-ray room, it's especially noticeable.

Therefore, if we implements the points described in the `Safe Blocked Off Areas` algorithm, we can create new rules that will allow the creation of closed, dead-end spaces, but prohibit placement that would lead to pathing errors in the game.

At the moment I have already developed 3.1 and 3.2.

<img width="451" height="531" alt="Image" src="https://github.com/user-attachments/assets/b86828f0-ff52-4696-99bd-33b51dac7dbb" />

**Comment by ARGAMX** [comment]
Support for blocking off areas in rooms: #3282

**Comment by ARGAMX** [comment]
Potential game crashes and bugs (such as teleportation) due to blocked areas can be solved by simply preventing the creation of such blocked areas.

`allow_blocking_off_areas = false` did exactly that. It prevented the creation of any areas unconnected to the outside world. However, there's a catch: it's too restrictive compared to the original game. It prevents the creation of any blocked areas at all, even if they don't contain any objects of interest to patients or doctors.

In the original game, it was possible to block some empty areas, but only if certain conditions were met. However, Bullfrog managed to introduce bugs in the checking of these conditions, and sometimes, under the same conditions, the same area could be blocked and sometimes not.

Based on this, blocking of areas can be implemented, but only by fulfilling certain checks. But which ones exactly...

Initially, this task had a section titled "Fix bugs that arise because a part of the map is blocked off."
I wasn't sure where these bugs were supposed to come from. What bugs?
Why couldn't we just follow fairly "safe" placement rules from the start, so that invalid placements simply couldn't be made and then nothing would need to be fixed? Why fix something that can be prevented?

In the original game, when placing objects in a room, you're limited by the following conditions:
1. When placing an object, its access points must be accessible from the room door.
2. When placing an object, the access points of other objects already in the room must remain accessible from the room door.
3. When placing an object, humanoids in the room must have at least one possible path to the door.

#3282 practically implements exactly these rules for rooms, with the exception that point 3 is made more stringent.

This way, humanoids can't be blocked in rooms. It seems quite reasonable and safe!
It's convenient and simple. You can't block anything—so what problems or bugs could arise from blocking? Only if the checks are implemented incorrectly.

So I couldn't understand why, for example, someone should create an invalid room in CorsixTH, which couldn't be built in the original game, where the doctor teleports himself or teleports objects, and then fixed the resulting bugs? Why, if such a room should be impossible in principle? No invalid room—no problem. It's like shooting yourself in the foot and then analysing how to treat the foot after the wound.

But there's a catch that makes some sense: the original game allows you to block humanoids in hallways!
So, you can't block humanoids in rooms, but you can in hallways. Which, admittedly, is quite unsafe. The question is why.

It turns out that hallways have different security requirements than rooms. And if we follow the rules of the original game, then humanoids need to be able to handle situations where they find themselves in a dead end and can't find a route. In a room, this was completely unnecessary. But in hallways, it makes sense.

But humanoids generally build routes and walk the same way, whether in rooms or hallways. So, a humanoid generally doesn't care where they're blocked.
So, it makes sense to deliberately create "defective situations" (when someone is blocked), but mostly in hallways, not in rooms.

And CorsixTH currently handles situations where a humanoid has route problems very poorly. Humanoid movement in CorsixTH was designed more for near-perfect conditions, where nothing is blocked and there's always a path. The only thing the walking algorithm in CorsixTH can do is rebuild a route along an alternate path if obstacles appear on the old path that prevent the humanoid from following its previously established route.

I'm not sure we should allow blocking humanoids, though.
It's unclear what this does for the player or the gameplay. Taunting a patient?
The only more or less acceptable use for blocking patients in hallways that I know is to manipulate the movement of infected patients.
Perhaps that makes some sense.
Therefore, it seems we shouldn't rule out the possibility of blocking patients.
I couldn't turn Handyman into Chewbacca. And I don't understand why somebody need to do that.

I tried blocking parts of the hospital and humanoids in CorsixTH, and I encountered several types of crashes and errors.

In response to these situations, I made several code improvements that, I believe, help the game be more stable and resilient to such situations, preventing crashes. Several subsequent tasks and a PR will be devoted to this.

When working on PR #3282, I wasn't planning on doing this, and at the time it seemed unnecessary. But now I no longer think so. And after this should a relatively secure algorithm for blocking some of the hospital corridors be implemented.

**Comment by TheCycoONE** [comment]
One use that is often mentioned in tip/strategy guides is to prevent leaving during an epidemic.

**Comment by ARGAMX** [comment]
Hello again. 👋

I experimented with blocked areas outside of rooms in the original TH and got very inconsistent results.

In most cases, you can block an area of ​​any size with any object, as long as there's nothing in that area.

Make yourself some ~~coffee~~ tea, Interesting discoveries await you.

Let's start with the simple.

-----------

'1. For example, you could take 12 benches and place them with their backs around the 3x3 area, creating a 3x3 blocked area.

<img width="325" height="210" alt="Image" src="https://github.com/user-attachments/assets/b55bbced-98c0-4eaa-a487-bc846251d44e" />

.
So it is possible to create a blocked empty area by objects.

-----------

'2. Now, if we try to put a staff member into this blocked area, we won't be able to.

<img width="332" height="228" alt="Image" src="https://github.com/user-attachments/assets/91d898e3-f74f-4be3-a2e4-514b47f31ee4" />

.
Does it mean that a staff member can't be in the blocked area?

-----------

'3. But if we throw a staff member in first and then start blocking that area with benches, we can block the staff member inside.

<img width="321" height="216" alt="Image" src="https://github.com/user-attachments/assets/7b35527d-e31c-4f6e-93e7-69a6f58b89e2" />

.
Does it mean that a staff member can be in the blocked area?

Are you starting to get it yet?
Wait, this is just the beginning of the fun. We're just warming up.

-----------

'4. Now, let's let the doctor relax after such stress and continue with the extinguisher. if we place a fire extinguisher in the center and surround it with benches in a 3x3 area, we won't be able to block this area. 

<img width="326" height="228" alt="Image" src="https://github.com/user-attachments/assets/bef30329-27c2-4a78-9c50-b3b759e27e1f" />

.
What does this mean? You can't block fire extinguishers? 
But a humanoid can't interact with extinguishers directly, right? What's the point of this?
You also can't block heaters, drink machines, reception desks, or benches — they're just like fire extinguishers — they can't be blocked.

-----------

'5. But Plants... if we place a plant and surround it with benches in 9x9, it is ok! We can even pick up that plant and put it back in the blocked area! Handyman won't be able to reach it and water it, but there won't be any placement restrictions! 

<img width="348" height="236" alt="Image" src="https://github.com/user-attachments/assets/5ec0b401-f56a-4374-a072-52b3495ffbcf" />

.
What does this mean? User allowed to place plants in the blocked area? 
What about Handyman who want to water them?..

-----------

'6. So, fire extinguishers, heaters, drink machines, the reception desk, and benches — can't they be blocked?
But we can block areas not only with objects, but also with rooms.
Let's place 9 benches around the perimeter, covering three sides, leaving one side free.
Now let's place a fire extinguisher in the center. And now let's block the final third side with a room.

<img width="507" height="380" alt="Image" src="https://github.com/user-attachments/assets/90471816-67ee-445c-8f44-60b2794fa732" />

.
As you can see no problem here!
What does this mean? Does it mean that fire extinguishers can still be in a blocked area?
Does this also mean that we can create any blocked areas by building rooms?

-----------

'7. What if we build a room with a door facing inward?

<img width="513" height="386" alt="Image" src="https://github.com/user-attachments/assets/5c488a76-d52e-4380-8ae3-772156a1cffe" />

.
That's allowed.
Does this mean that a room can be placed with its door facing inward into a blocked area?

-----------

'8. Continuing with the previous point, let's remove three benches from one side. 
And let's try building second room.

<img width="676" height="410" alt="Image" src="https://github.com/user-attachments/assets/783cc91c-6ce9-477f-841e-c3a9a3293e70" />

.
Not possible anymore! And neither with the door facing outward nor inward. 
We won't even help you get to the door placement stage.
Unable to press button and move to the next build stage. Adviser is complaining.
Does this mean a room can't be placed with its door facing inward into a blocked zone?

Is your head hurting already?
We're probably over the worst of it. But we're not done yet...

-----------

'9. Let's try building a room first, and then blocking its door with objects.

<img width="483" height="352" alt="Image" src="https://github.com/user-attachments/assets/4d7f2017-d956-49ce-a3cc-e6d8647dcaad" />

.
This can't be done.
Does this mean a room can't be placed with its door facing inward into a blocked zone?

-----------

'10. Let's try creating a blocked zone with only rooms.

<img width="665" height="482" alt="Image" src="https://github.com/user-attachments/assets/7bd8419e-b6d5-4fa0-b2c9-e8e229a30a05" />

.
This way allowed.

When building a room, there's a check that no other room's door should be in the blocked zone.
Therefore, we can't block another room with a new room.
But there's no check that the new room will be a door faced to a blocked zone.
However, we can block a fire extinguisher, a soda machine, or a bench in this zone. 
But we can't block the reception table in this zone.

-----------

'11. Continuing with the previous point.
And now for the icing on the cake!
Buy any object and try placing it anywhere in the hallway. 
For example, a plant.

<img width="765" height="473" alt="Image" src="https://github.com/user-attachments/assets/c018374b-d867-45fa-8329-193cd5e2c378" />

.
You won't be able to do it. You can't place the object.
And if you pick up one of the existing objects, you can't put it back!
And you won't be able to build any more rooms.
Congratulations, you just broke the game!!!
Write to Bullfrog - I think they'll be happy to hire you as a tester.
Oh, wait...

-----------

Tell me what you feel and think in this place?
I'm really interested.

And we're still not done...
We're not done with humanoids yet.

-----------

'12. Continuing with the previous step,
Hire a nurse.
She can be placed anywhere except in the blocked area between rooms.
However, she can be placed in a room with door leads into the blocked area!
Although the room is essentially part of this blocked area, we place the nurse in this room.

<img width="713" height="469" alt="Image" src="https://github.com/user-attachments/assets/9ec40eaa-0c55-4025-aad9-6fbb34a87949" />

.
Now we select "Edit Room" and try to enter editing mode for this room.
This kicks the nurse out of the room.
That's it, she's in the blocked area inside!
Although we couldn't place her there, she'll go there herself.

<img width="707" height="498" alt="Image" src="https://github.com/user-attachments/assets/4cae3bd7-6fb7-47c3-bf98-1d7a4b0d41d0" />

.
Where is the logic here?

-----------

'13. And then there's another annoying glitch. This nurse is in a blocked area.
She can't access other rooms. But for some reason, she takes calls to other rooms!
By taking a call to another room, she blocks other available nurses from entering that room.

<img width="542" height="477" alt="Image" src="https://github.com/user-attachments/assets/b77e245e-cf87-469d-a817-2f8e618ca703" />

.
In fact, a queue is building up in front of that room, and no staff comes to serve that room,
even though there are plenty of available nurses milling about in the hallway. 
And that blocked nurse will never come to that room.
In my opinion, this is clearly broken behavior.

-----------

'14. If you also place Handyman in that room, he also takes tasks and can't complete them. 
Here he is, trying to fix the Scanner.

<img width="341" height="251" alt="Image" src="https://github.com/user-attachments/assets/9fccf1e8-ee1a-4ac5-a45a-949ee035094f" />

.
Although, apparently, Handyman can steal tasks from each other in the original TH.
I still don't like the fact that a blocked Handyman takes tasks.

-----------

This is another clear example of how Bullfrog hasn't polished the area blocking functionality properly.
And knowing this, should we try to replicate it, potentially introducing similar defects and consequences?
We won't have the option to "look and do it like the original," because it doesn't work well in the original.

That's why I'm skeptical about allowing blocked areas with humanoids in hallways, as in the original game.
The way they implemented blockers in rooms is quite adequate.
The way they implemented blockers in hallways is very poor.

First, it's inconsistent.
Second, it's clearly buggy.

That's precisely why I'm skeptical about replicating this dangerous logic in CorsixTH,
And instead, it might be better to create our own, more reliable one.

Okay, maybe it's not that bad. But at least you know this now.

-----------

When any humanoid moves along a hallway, it can be surrounded by objects.
This will trap it in a blocked area.

I hired about six Handymen and blocked them, not in a 1x1 area, but in a larger area. I waited for several years. 
But they never transformed into anything.

That seems to be it. Am I missing anything?

Another bugs I catched during this exploration:

<img width="238" height="273" alt="Image" src="https://github.com/user-attachments/assets/bfe83d19-00a5-4d53-a48d-3402a4467828" />

.
255?

<img width="385" height="577" alt="Image" src="https://github.com/user-attachments/assets/598a806e-d63e-4b23-899a-059644c61531" />

.
And how long has baldness been treated in pharmacies?

-----------

Ok, so let's recap:

1. You can't build rooms in a blocked area.
2. You can build rooms in a blocked area.
3. You can't place objects in a blocked area.
4. You can place objects in a blocked area.
5. Humanoids cannot be in a blocked area.
6. Humanoids can be in a blocked area.

Clear, simple, easy to remember!
And most importantly, it's all confirmed by experiments.
If you want to have an interesting evening, be sure to repeat these experiments!

-----------

Okay, now let's get serious, final recap:

1. You can't build rooms in a blocked area. Room doors can't be in a blocked area. Bullfrog clearly tried to ensure that it's impossible to make a room isolated. The only thing they failed to do was check when building a room that the room itself doesn't have a door leading to a blocked area. If you do, the game breaks.

2. Regarding placing and having objects in a blocked area. This is more complicated. It seems like we could allow plants to be placed in a blocked area. It seems harmless enough, except that Handyman will be scratching his head how to water it. But the thought of placing a reception desk in a blocked area makes me sick. Benches and soda machines — I'm torn, I don't know. Radiators, fire extinguishers, trash cans — I don't see why they should't be allowed. But it would certainly be easier to restrict everything indiscriminately. Let's think about it.

3. Regarding placing and having humanoids in a blocked area. I'm still a little queasy about the idea. Okay, I'm already working on making humanoids more adaptable to being in blocked areas so they don't crash the game. So let's try to allow it at first and see what will happens. I think we will have the option to disable/enable that ability.

That's the story.
Why can't put reactions to messages in this section?

**Comment by ARGAMX** [comment]
Algorithm for checking the possibility of placing an object in hallways taking into account the blocking of zones:

Input:
We have `target_XY`, the potential placement point.
We have the footprint of the object being placed.
We have `world.spawn_points`, the points where patients spawns happen.

1. Step 1.

This step performs all the usual checks to ensure that the object can fit this place.

These checks are already in the code. Nothing new needs to be implemented here.

If the object cannot be placed, terminate the function. Placement is prohibited ❌.
Otherwise, proceed to step 2.

-------------------

2. Step 2.

New code begins here.
First, let's check whether placing an item creates blocked zones.
Keep in mind that placing an item could hypothetically create not just one, but several blocked zones.

Get `spawn_tiles` from `world.spawn_points`.
Check whether all `spawn_tiles` are accessible from `target_XY` using `getPathDistance`.
If at least one `spawn_tile` is not accessible from `target_XY`, then
this is already a blocked-off area. Reception Desk can not be placed here. Other objects can.
If this Reception Desk then Terminate the function. Placement is prohibited ❌.
Otherwise continue.

Get the vertical and horizontal points around the object's footprint on `target_XY` (the so-called `adjacent_to_solid_footprint`). 
Let's call them `adjacent_tiles`.

We filter out `adjacent_tiles` that are already occupied — they already have objects on them, or they're behind the hospital wall. We're not interested in these filtered `adjacent_tiles`. We leave the rest in `adjacent_tiles_2`.

🦶 We overlay the object's footprint on `target_XY`. (As if the placement had already occurred.) 
From now on, everything will look as if the object was placed.

We create a new array of `scattered_areas` for XY, each XY representing a new blocked area.
The array is empty for now.

We loop through `adjacent_tiles_2`. (for `tile_2` in `adjacent_tiles_2`)
In the loop, we check whether each point in `scattered_areas` is reachable from point `tile_2` using `getPathDistance`.
If at least one point in `scattered_areas` has a path to `tile_2`, we discard `tile_2` — it's not of interest to us.
If no point in `scattered_areas` has a path to `tile_2`, then we store `tile_2` in `scattered_areas`.
Here, the loop body (for `tile_2` in `adjacent_tiles_2`) ends.

This will give us an array `scattered_areas` containing only those `adjacent_tiles_2` that are not connected to each other.
Each of them will represent an area that is not connected to the others.

We create a new array of `blocked_areas` for XY.
The array is empty for now.

Now we loop through `scattered_areas`.
We check each XY point in `scattered_areas` for accessibility using `getPathDistance` with each point in `spawn_tiles`.
In the loop body, we check:
If no tile in `spawn_tiles` is accessible from XY, then this tile is a typical blocked area. We store it in `blocked_areas`.
If all tiles in `spawn_tiles` are accessible from XY, then this tile is part of the main open world area. We do not store it in `blocked_areas`. Discard.
If some tiles from `spawn_tiles` are accessible from XY and some are not, then placing the object divides the hospital into several areas capable of functioning independently. This is unacceptable. 🦶 Remove the item's footprint from `target_XY`. End the function. Placement is prohibited ❌.
Otherwise continue.
The loop body ends here.

This will give us the `blocked_areas` array, which stores one point from each newly created blocked area.
If the `blocked_areas` array contains 0 elements, then placing the object does not create any blocked areas.
If the `blocked_areas` array contains 1 element, then placing the object creates 1 blocked area.
If the `blocked_areas` array contains N elements, then placing the object creates N blocked areas.

This tells us whether and how many blocked areas are created during placement.

If the `blocked_areas` array contains 0 elements, then 🦶 Remove the item's footprint from `target_XY`. (As if the item had been removed.) End the function. Placement is allowed ✅.
Otherwise If there are 1 or more elements in the `blocked_areas` array, go to step 3.

-------------------

3. Step 3.

Here comes the real meat – we need to check if there are any prohibited objects in the created blocked area.
Take the first XY from `blocked_areas`

The tiles in blocked area of ​​the hospital is a typical graph.
Each tile is a `Node`. Each `Edge` is a neighboring passable connection between tiles.
Next, we traverse the graph using known graph traversal methods.
Save the tiles visited. Next, we move to neighboring tiles accessible via passable connections.
If we visit a tile twice, we skip it.
When visiting a tile, we check for prohibited objects.
If at least one prohibited object is found, we terminate the function. 🦶 Remove the item's footprint from `target_XY`. Placement is prohibited ❌.
Otherwise continue.

This algorithm seems quite intensive, which can put a strain on Lua on big maps. Therefore, I'm unsure whether it should be implemented in Lua or whether it should be written in C.

If there are multiple blocked areas (multiple elements in the `blocked_areas` array), repeat the algorithm for each area.

If all areas and all tiles within these areas have been examined and nothing prohibited is found, then
Congratulations! This placement creates a blocked area. However, placement is still allowed. ✅ Finish executing the function.
🦶 Remove the item's footprint from `target_XY`. (As if the item had been removed.)

-------------------

This is about object placement.
Now about room building.

When building a room, the logic is as follows:
1. The room's outer door tile must be accessible to all `world.spawn_points`.
If not, either prevent the door from being placed that way or prevent the player from proceeding to the next build phase.
2. When placing the room blueprint and try to move to the next build phase, use "adjacent_to_room_walls_tiles" around room and perform the same check as in Steps 2 and Steps 3 for object. If the check fails - prevent the player from proceeding to the next build phase.

-------------------

What do you think on this?

**Comment by TheCycoONE** [comment]
I'm interested in supporting unreachable regions of the hospital, the handiman easteregg, the door blocking and unheated hospital blocking strategies.

I'm not interested in replicating the Theme Hospital algorithm. We don't need to prevent blocking radiators or extinguishers, or even room doors I suppose.

Undecided on the staff call to unteachable room. There's room for improvement, like path checking on call and calling someone else if they are stuck.

**Comment by mugmuggy** [comment]
TH obviously had compute time limitations, as well as storage to contend with. Its path finding, and its been a while since I looked at, only has 7 points recorded max, those points are not the exact path, but are something like each 'triangle', ie a movement in the X or Y direction and then a movement in the Y or X respectively. Assuming nothing changes on the path, when the last element is reached, it is checked against the destination co-ordinates. I never confirmed it, but I suspect there is a distance check as well.  Ie TH just stops looking at somepoint.

TH itself when building rooms is also bugged, because the door being placed doesn't exist yet and isn't checked for the accessibility. It checks all other doors are connectable and the door to the hospital itself.

**Comment by ARGAMX** [comment]
Today I was again thinking about blocking humanoids.
If we allow to block them it is possible to block the Health Inspector then?
That way, the epidemic will get stuck and never end.
And subsequent epidemics will never be able to start.
This behavior doesn't seem pretty valid to me.
Blocking epidemiological patients is also still a bit of kind a dirty hack.

**Comment by lewri** [comment]
> Today I was again thinking about blocking humanoids. If we allow to block them it is possible to block the Health Inspector then? That way, the epidemic will get stuck and never end. And subsequent epidemics will never be able to start. This behavior doesn't seem pretty valid to me. Blocking epidemiological patients is also still a bit of kind a dirty hack.

To answer that question, I believe it was a valid tactic in TH. That is not a comment on what is the right thing to do though.

**Comment by ARGAMX** [comment]
> Algorithm for checking the possibility of placing an object in hallways taking into account the blocking of zones:

I will describe the same thing, but with fewer technical details—as a requirement for the task: 

In the original Theme Hospital checks performed during object placement and room construction allow players to create enclosed spaces / blocked off areas — cut off from the rest of the hospital and inaccessible to humanoids on foot — while simultaneously ensuring that critical objects requiring humanoid interaction do not end up inside such areas.

In reality, these checks sometimes malfunctioned in the original *Theme Hospital*, allowing the player to build a room with a door that was impossible to reach. But let's just treat those as bugs in the original game — things that shouldn't have happened.

To clarify once more, enclosed spaces / blocked off areas - are areas cut off from the rest of the hospital that humanoids cannot enter on foot, because the `pathfinder:findPath` function cannot generate a path into such an area from the rest of the hospital.

If such an area has a path to all the patient respawn points on the current map, that section is not considered blocked.

In CorsixTH, it was originally strictly forbidden to create any enclosed spaces / blocked off areas. Consequently, it was impossible to build some room layouts that were possible in the original game (provided that allow_blocking_off_areas = false).

It was possible to disable this restriction, but there were no safeguards in place to prevent important objects — with which humanoids interact — from ending up in such a blocked area (by setting `allow_blocking_off_areas = true`). However, after that, the game might start throwing pathfinding errors and crash.

PR #3282 "Support for blocking off areas in rooms" added the ability to create enclosed spaces / blocked off areas when placing objects in a room and to perform checks just like in the original *Theme Hospital* game. The `allow_blocking_off_areas` setting has been renamed to `blocking_off_areas` and now supports three possible values. Please refer to the PR 3282 changes for a detailed explanation of each option. https://github.com/CorsixTH/CorsixTH/pull/3282

Thanks to PR #3282, CorsixTH now applies the same object placement rules during placing objects in a room as the original game. However, hospital corridors remain unchanged: setting `allow_blocking_off_areas` to 1 and 2 simply prevents the creation of enclosed spaces within the corridors.

The objective is to implement functionality in CorsixTH — specifically for `allow_blocking_off_areas = 2` — that enables the creation of safe, enclosed spaces within corridors, subject to the necessary checks.

The following terminology will be used regarding the frequency and timing of these checks:

Early and Final Check – the check runs whenever the blueprint or ghost image of the object being shown or redrawn at a new potential installation location/coordinate. This means the user can see beforehand, via the blueprint or ghost image, that placement is not allowed there. If the user proceeds to click and attempt placement or move to the next stage, a Final Check is also performed, which prevents the placement from occurring. The Early Check is required solely to correctly render the blueprint or ghost image of the object being placed; it offers better responsiveness for the user but executes in advance, before any click occurs.

Final Check Only – the check runs only at the moment the user attempts to place the object or proceed to the next stage of room construction. Consequently, the blueprint or ghost image might appear valid, but the process halts upon clicking. The Final Check is less responsive for the user, as it executes only after the click.

`allow_blocking_off_areas = 3 Bypass` – indicates that if this check disallows placement but `allow_blocking_off_areas = 3` is set, the placement/construction is permitted, and the following command is executed: `TheApp.world:gameLog("Warning: Blocking off areas is allowed at " .. x .. ", " .. y .. ".")`

So, the placement rules themselves are as follows:

1. A room door cannot be located within an enclosed, blocked-off area.
1.1. This must be checked when selecting the door location during room construction — specifically, it should be impossible to choose a location that results in such a state when placing the door blueprint. Early and Final checks. `allow_blocking_off_areas = 3 Bypass`.
1.2. This must also be checked when constructing other rooms to ensure that the new room's walls do not create an enclosed space around the doors of existing rooms; this check applies when the blueprint has been selected and the user clicks the button to proceed to the next construction stage (where the new room's door location is chosen). Final check only. `allow_blocking_off_areas = 3 Bypass`.
1.3. This must also be checked when placing objects in a corridor to ensure that installing an object does not create an enclosed, blocked-off zone containing a door. Final check only. `allow_blocking_off_areas = 3 Bypass`.

2. Corridor objects can be placed in an enclosed, blocked-off area. Examples include plants, a vending machine, a bench, a radiator, a fire extinguisher, and a trash can. The Reception Desk is an exception. The Reception Desk has a specific tile where the receptionist approaches and works, and another tile that patients approach. Neither of these tiles can be cut off from the map's spawn points.
2.1. We must verify this when building rooms—specifically, that the new room's walls do not block the Reception Desk. Final check only. `allow_blocking_off_areas = 3 Bypass`.
2.2. We must also verify this when placing other objects in the corridor to ensure that previously placed Reception Desks do not become inaccessible. Final check only. `allow_blocking_off_areas = 3 Bypass`.

3. For Humanoids. A flag named "allow_blocking_off_humanoids" must be used for humanoids. This flag can only be toggled by editing the Lua file.
3.1. If "allow_blocking_off_humanoids" is set to `false`, humanoids must not end up in an enclosed space / blocked off area.
3.1.1. Staff members who can be picked up and placed elsewhere cannot be placed in a blocked-off area. Final check only.
3.1.2. Room construction check: ensure the new room's walls do not block anyone in. Final check only. `allow_blocking_off_areas = 3 Bypass`.
3.1.3. Corridor object placement check: ensure no humanoid gets blocked in when placing an object. Final check only. `allow_blocking_off_areas = 3 Bypass`.
3.2. If "allow_blocking_off_humanoids" is set to `true`, humanoids are permitted to end up in an enclosed space / blocked off area.
3.2.1. Staff members who can be picked up and placed elsewhere still cannot be placed in a blocked-off area. In other words, intentionally dropping a humanoid into a trap remains prohibited. Final check only.
3.2.2. The room construction check does not prevent blocking a humanoid; the new room's walls may block someone in.
3.2.3. The corridor object placement check does not prevent blocking a humanoid; a humanoid may end up blocked in when an object is placed.

**Comment by ARGAMX** [comment]
> One use that is often mentioned in tip/strategy guides is to prevent leaving during an epidemic.

> I'm interested in supporting unreachable regions of the hospital, the handiman easteregg, the door blocking and unheated hospital blocking strategies.

"blocking and unheated hospital blocking strategies" — true, I see that as one of the main goals.

Handyman Easter egg — there are issues with that for now.
I’d appreciate it if someone could send me a video or a save file with handyman so I could investigate this behavior in the original game. So far, it just looks like a rumor to me; I haven’t been able to reproduce it, and I’ve never seen it myself.

Blocking the Health Inspector seems like a rather crude tactic. Moreover, doing so in CorsixTH creates issues for subsequent emergency events, which—by all appearances—will fail to trigger properly.

Related to deliberately trapped humanoid the main catch is that our current humanoids behavior not robust enough to call safe.

I had previously started development in this direction in #3337 and #3332, but I kept running into new problems. This is a separate area.

At this stage, I believe that implementing deliberately trapped humanoid reliably would require significant additional work.

The task of creating "safe blocked area" is substantial in its own right; adding this extra requirement would make it unmanageably large. We would become overwhelmed, both during development and at the PR stage.

Therefore, I am currently inclined to implement blocked areas in the safest way:
Humanoids are prohibited from being in blocked areas.

Only after we have developed, tested, and merged this—and then put it through its paces in a release build—only then I think it would make sense to attempt to tackle the actual blocking of humanoids.

At the moment, I am exclude a completed solid deliberately trapped humanoid functional as goal from the task.

For now, I plan to only add a flag in the code that makes it easy to enable/disable this possibility. However, enable this possibility and deliberately trap any humanoid high likely will cause the Lua to crash.
